#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3634
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="landrover")]
	public partial class LandRoverOldDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertusers(users instance);
    partial void Updateusers(users instance);
    partial void Deleteusers(users instance);
    partial void Insertshijia1(shijia1 instance);
    partial void Updateshijia1(shijia1 instance);
    partial void Deleteshijia1(shijia1 instance);
    partial void Insertshouce(shouce instance);
    partial void Updateshouce(shouce instance);
    partial void Deleteshouce(shouce instance);
    #endregion
		
		public LandRoverOldDbDataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["landroverConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LandRoverOldDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LandRoverOldDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LandRoverOldDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LandRoverOldDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<users> users
		{
			get
			{
				return this.GetTable<users>();
			}
		}
		
		public System.Data.Linq.Table<shijia1> shijia1
		{
			get
			{
				return this.GetTable<shijia1>();
			}
		}
		
		public System.Data.Linq.Table<shouce> shouce
		{
			get
			{
				return this.GetTable<shouce>();
			}
		}
	}
	
	[Table(Name="dbo.users")]
	public partial class users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
		private string _age;
		
		private string _city;
		
		private string _sex;
		
		private string _email;
		
		private string _dianhua;
		
		private string _shouji;
		
		private string _address;
		
		private string _youbian;
		
		private string _sheng;
		
		private System.Nullable<double> _enews;
		
		private System.Nullable<System.DateTime> _times;
		
		private string _receive;
		
		private string _phone;
		
		private string _carStyle;
		
		private string _oftenGo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnageChanging(string value);
    partial void OnageChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndianhuaChanging(string value);
    partial void OndianhuaChanged();
    partial void OnshoujiChanging(string value);
    partial void OnshoujiChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnyoubianChanging(string value);
    partial void OnyoubianChanged();
    partial void OnshengChanging(string value);
    partial void OnshengChanged();
    partial void OnenewsChanging(System.Nullable<double> value);
    partial void OnenewsChanged();
    partial void OntimesChanging(System.Nullable<System.DateTime> value);
    partial void OntimesChanged();
    partial void OnreceiveChanging(string value);
    partial void OnreceiveChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OncarStyleChanging(string value);
    partial void OncarStyleChanged();
    partial void OnoftenGoChanging(string value);
    partial void OnoftenGoChanged();
    #endregion
		
		public users()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_username", DbType="NVarChar(255)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[Column(Storage="_password", DbType="NVarChar(255)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[Column(Storage="_age", DbType="NVarChar(255)")]
		public string age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		[Column(Storage="_city", DbType="NVarChar(255)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[Column(Storage="_sex", DbType="NVarChar(255)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="NVarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[Column(Storage="_dianhua", DbType="NVarChar(255)")]
		public string dianhua
		{
			get
			{
				return this._dianhua;
			}
			set
			{
				if ((this._dianhua != value))
				{
					this.OndianhuaChanging(value);
					this.SendPropertyChanging();
					this._dianhua = value;
					this.SendPropertyChanged("dianhua");
					this.OndianhuaChanged();
				}
			}
		}
		
		[Column(Storage="_shouji", DbType="NVarChar(255)")]
		public string shouji
		{
			get
			{
				return this._shouji;
			}
			set
			{
				if ((this._shouji != value))
				{
					this.OnshoujiChanging(value);
					this.SendPropertyChanging();
					this._shouji = value;
					this.SendPropertyChanged("shouji");
					this.OnshoujiChanged();
				}
			}
		}
		
		[Column(Storage="_address", DbType="NVarChar(255)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[Column(Storage="_youbian", DbType="NVarChar(255)")]
		public string youbian
		{
			get
			{
				return this._youbian;
			}
			set
			{
				if ((this._youbian != value))
				{
					this.OnyoubianChanging(value);
					this.SendPropertyChanging();
					this._youbian = value;
					this.SendPropertyChanged("youbian");
					this.OnyoubianChanged();
				}
			}
		}
		
		[Column(Storage="_sheng", DbType="NVarChar(255)")]
		public string sheng
		{
			get
			{
				return this._sheng;
			}
			set
			{
				if ((this._sheng != value))
				{
					this.OnshengChanging(value);
					this.SendPropertyChanging();
					this._sheng = value;
					this.SendPropertyChanged("sheng");
					this.OnshengChanged();
				}
			}
		}
		
		[Column(Storage="_enews", DbType="Float")]
		public System.Nullable<double> enews
		{
			get
			{
				return this._enews;
			}
			set
			{
				if ((this._enews != value))
				{
					this.OnenewsChanging(value);
					this.SendPropertyChanging();
					this._enews = value;
					this.SendPropertyChanged("enews");
					this.OnenewsChanged();
				}
			}
		}
		
		[Column(Storage="_times", DbType="DateTime")]
		public System.Nullable<System.DateTime> times
		{
			get
			{
				return this._times;
			}
			set
			{
				if ((this._times != value))
				{
					this.OntimesChanging(value);
					this.SendPropertyChanging();
					this._times = value;
					this.SendPropertyChanged("times");
					this.OntimesChanged();
				}
			}
		}
		
		[Column(Storage="_receive", DbType="VarChar(10)")]
		public string receive
		{
			get
			{
				return this._receive;
			}
			set
			{
				if ((this._receive != value))
				{
					this.OnreceiveChanging(value);
					this.SendPropertyChanging();
					this._receive = value;
					this.SendPropertyChanged("receive");
					this.OnreceiveChanged();
				}
			}
		}
		
		[Column(Storage="_phone", DbType="NChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[Column(Storage="_carStyle", DbType="NChar(50)")]
		public string carStyle
		{
			get
			{
				return this._carStyle;
			}
			set
			{
				if ((this._carStyle != value))
				{
					this.OncarStyleChanging(value);
					this.SendPropertyChanging();
					this._carStyle = value;
					this.SendPropertyChanged("carStyle");
					this.OncarStyleChanged();
				}
			}
		}
		
		[Column(Storage="_oftenGo", DbType="NVarChar(100)")]
		public string oftenGo
		{
			get
			{
				return this._oftenGo;
			}
			set
			{
				if ((this._oftenGo != value))
				{
					this.OnoftenGoChanging(value);
					this.SendPropertyChanging();
					this._oftenGo = value;
					this.SendPropertyChanged("oftenGo");
					this.OnoftenGoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.shijia1")]
	public partial class shijia1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _sex;
		
		private string _username;
		
		private string _date;
		
		private string _sheng;
		
		private string _city;
		
		private string _address;
		
		private string _youbian;
		
		private string _email;
		
		private string _dianhua;
		
		private string _shouji;
		
		private string _chexing;
		
		private string _sjsj;
		
		private string _jxssf;
		
		private string _jxscs;
		
		private string _jxs;
		
		private string _lxfs;
		
		private System.Nullable<System.DateTime> _times;
		
		private string _gcsj;
		
		private string _gcys;
		
		private string _phcx;
		
		private string _phcx1;
		
		private string _phcx2;
		
		private string _phcx3;
		
		private string _phcx4;
		
		private System.Nullable<bool> _owner;
		
		private string _boughtdate;
		
		private string _carbrand;
		
		private string _carmodel;
		
		private string _brochure;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OnshengChanging(string value);
    partial void OnshengChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnyoubianChanging(string value);
    partial void OnyoubianChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndianhuaChanging(string value);
    partial void OndianhuaChanged();
    partial void OnshoujiChanging(string value);
    partial void OnshoujiChanged();
    partial void OnchexingChanging(string value);
    partial void OnchexingChanged();
    partial void OnsjsjChanging(string value);
    partial void OnsjsjChanged();
    partial void OnjxssfChanging(string value);
    partial void OnjxssfChanged();
    partial void OnjxscsChanging(string value);
    partial void OnjxscsChanged();
    partial void OnjxsChanging(string value);
    partial void OnjxsChanged();
    partial void OnlxfsChanging(string value);
    partial void OnlxfsChanged();
    partial void OntimesChanging(System.Nullable<System.DateTime> value);
    partial void OntimesChanged();
    partial void OngcsjChanging(string value);
    partial void OngcsjChanged();
    partial void OngcysChanging(string value);
    partial void OngcysChanged();
    partial void OnphcxChanging(string value);
    partial void OnphcxChanged();
    partial void Onphcx1Changing(string value);
    partial void Onphcx1Changed();
    partial void Onphcx2Changing(string value);
    partial void Onphcx2Changed();
    partial void Onphcx3Changing(string value);
    partial void Onphcx3Changed();
    partial void Onphcx4Changing(string value);
    partial void Onphcx4Changed();
    partial void OnownerChanging(System.Nullable<bool> value);
    partial void OnownerChanged();
    partial void OnboughtdateChanging(string value);
    partial void OnboughtdateChanged();
    partial void OncarbrandChanging(string value);
    partial void OncarbrandChanged();
    partial void OncarmodelChanging(string value);
    partial void OncarmodelChanged();
    partial void OnbrochureChanging(string value);
    partial void OnbrochureChanged();
    #endregion
		
		public shijia1()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_sex", DbType="NVarChar(255)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[Column(Storage="_username", DbType="NVarChar(255)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[Column(Storage="_date", DbType="NVarChar(255)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[Column(Storage="_sheng", DbType="NVarChar(255)")]
		public string sheng
		{
			get
			{
				return this._sheng;
			}
			set
			{
				if ((this._sheng != value))
				{
					this.OnshengChanging(value);
					this.SendPropertyChanging();
					this._sheng = value;
					this.SendPropertyChanged("sheng");
					this.OnshengChanged();
				}
			}
		}
		
		[Column(Storage="_city", DbType="NVarChar(255)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[Column(Storage="_address", DbType="NVarChar(255)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[Column(Storage="_youbian", DbType="NVarChar(255)")]
		public string youbian
		{
			get
			{
				return this._youbian;
			}
			set
			{
				if ((this._youbian != value))
				{
					this.OnyoubianChanging(value);
					this.SendPropertyChanging();
					this._youbian = value;
					this.SendPropertyChanged("youbian");
					this.OnyoubianChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="NVarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[Column(Storage="_dianhua", DbType="NVarChar(255)")]
		public string dianhua
		{
			get
			{
				return this._dianhua;
			}
			set
			{
				if ((this._dianhua != value))
				{
					this.OndianhuaChanging(value);
					this.SendPropertyChanging();
					this._dianhua = value;
					this.SendPropertyChanged("dianhua");
					this.OndianhuaChanged();
				}
			}
		}
		
		[Column(Storage="_shouji", DbType="NVarChar(255)")]
		public string shouji
		{
			get
			{
				return this._shouji;
			}
			set
			{
				if ((this._shouji != value))
				{
					this.OnshoujiChanging(value);
					this.SendPropertyChanging();
					this._shouji = value;
					this.SendPropertyChanged("shouji");
					this.OnshoujiChanged();
				}
			}
		}
		
		[Column(Storage="_chexing", DbType="NVarChar(255)")]
		public string chexing
		{
			get
			{
				return this._chexing;
			}
			set
			{
				if ((this._chexing != value))
				{
					this.OnchexingChanging(value);
					this.SendPropertyChanging();
					this._chexing = value;
					this.SendPropertyChanged("chexing");
					this.OnchexingChanged();
				}
			}
		}
		
		[Column(Storage="_sjsj", DbType="NVarChar(255)")]
		public string sjsj
		{
			get
			{
				return this._sjsj;
			}
			set
			{
				if ((this._sjsj != value))
				{
					this.OnsjsjChanging(value);
					this.SendPropertyChanging();
					this._sjsj = value;
					this.SendPropertyChanged("sjsj");
					this.OnsjsjChanged();
				}
			}
		}
		
		[Column(Storage="_jxssf", DbType="NVarChar(255)")]
		public string jxssf
		{
			get
			{
				return this._jxssf;
			}
			set
			{
				if ((this._jxssf != value))
				{
					this.OnjxssfChanging(value);
					this.SendPropertyChanging();
					this._jxssf = value;
					this.SendPropertyChanged("jxssf");
					this.OnjxssfChanged();
				}
			}
		}
		
		[Column(Storage="_jxscs", DbType="NVarChar(255)")]
		public string jxscs
		{
			get
			{
				return this._jxscs;
			}
			set
			{
				if ((this._jxscs != value))
				{
					this.OnjxscsChanging(value);
					this.SendPropertyChanging();
					this._jxscs = value;
					this.SendPropertyChanged("jxscs");
					this.OnjxscsChanged();
				}
			}
		}
		
		[Column(Storage="_jxs", DbType="NVarChar(255)")]
		public string jxs
		{
			get
			{
				return this._jxs;
			}
			set
			{
				if ((this._jxs != value))
				{
					this.OnjxsChanging(value);
					this.SendPropertyChanging();
					this._jxs = value;
					this.SendPropertyChanged("jxs");
					this.OnjxsChanged();
				}
			}
		}
		
		[Column(Storage="_lxfs", DbType="NVarChar(255)")]
		public string lxfs
		{
			get
			{
				return this._lxfs;
			}
			set
			{
				if ((this._lxfs != value))
				{
					this.OnlxfsChanging(value);
					this.SendPropertyChanging();
					this._lxfs = value;
					this.SendPropertyChanged("lxfs");
					this.OnlxfsChanged();
				}
			}
		}
		
		[Column(Storage="_times", DbType="DateTime")]
		public System.Nullable<System.DateTime> times
		{
			get
			{
				return this._times;
			}
			set
			{
				if ((this._times != value))
				{
					this.OntimesChanging(value);
					this.SendPropertyChanging();
					this._times = value;
					this.SendPropertyChanged("times");
					this.OntimesChanged();
				}
			}
		}
		
		[Column(Storage="_gcsj", DbType="VarChar(30)")]
		public string gcsj
		{
			get
			{
				return this._gcsj;
			}
			set
			{
				if ((this._gcsj != value))
				{
					this.OngcsjChanging(value);
					this.SendPropertyChanging();
					this._gcsj = value;
					this.SendPropertyChanged("gcsj");
					this.OngcsjChanged();
				}
			}
		}
		
		[Column(Storage="_gcys", DbType="VarChar(30)")]
		public string gcys
		{
			get
			{
				return this._gcys;
			}
			set
			{
				if ((this._gcys != value))
				{
					this.OngcysChanging(value);
					this.SendPropertyChanging();
					this._gcys = value;
					this.SendPropertyChanged("gcys");
					this.OngcysChanged();
				}
			}
		}
		
		[Column(Storage="_phcx", DbType="NVarChar(500)")]
		public string phcx
		{
			get
			{
				return this._phcx;
			}
			set
			{
				if ((this._phcx != value))
				{
					this.OnphcxChanging(value);
					this.SendPropertyChanging();
					this._phcx = value;
					this.SendPropertyChanged("phcx");
					this.OnphcxChanged();
				}
			}
		}
		
		[Column(Storage="_phcx1", DbType="VarChar(30)")]
		public string phcx1
		{
			get
			{
				return this._phcx1;
			}
			set
			{
				if ((this._phcx1 != value))
				{
					this.Onphcx1Changing(value);
					this.SendPropertyChanging();
					this._phcx1 = value;
					this.SendPropertyChanged("phcx1");
					this.Onphcx1Changed();
				}
			}
		}
		
		[Column(Storage="_phcx2", DbType="VarChar(30)")]
		public string phcx2
		{
			get
			{
				return this._phcx2;
			}
			set
			{
				if ((this._phcx2 != value))
				{
					this.Onphcx2Changing(value);
					this.SendPropertyChanging();
					this._phcx2 = value;
					this.SendPropertyChanged("phcx2");
					this.Onphcx2Changed();
				}
			}
		}
		
		[Column(Storage="_phcx3", DbType="VarChar(30)")]
		public string phcx3
		{
			get
			{
				return this._phcx3;
			}
			set
			{
				if ((this._phcx3 != value))
				{
					this.Onphcx3Changing(value);
					this.SendPropertyChanging();
					this._phcx3 = value;
					this.SendPropertyChanged("phcx3");
					this.Onphcx3Changed();
				}
			}
		}
		
		[Column(Storage="_phcx4", DbType="VarChar(30)")]
		public string phcx4
		{
			get
			{
				return this._phcx4;
			}
			set
			{
				if ((this._phcx4 != value))
				{
					this.Onphcx4Changing(value);
					this.SendPropertyChanging();
					this._phcx4 = value;
					this.SendPropertyChanged("phcx4");
					this.Onphcx4Changed();
				}
			}
		}
		
		[Column(Storage="_owner", DbType="Bit")]
		public System.Nullable<bool> owner
		{
			get
			{
				return this._owner;
			}
			set
			{
				if ((this._owner != value))
				{
					this.OnownerChanging(value);
					this.SendPropertyChanging();
					this._owner = value;
					this.SendPropertyChanged("owner");
					this.OnownerChanged();
				}
			}
		}
		
		[Column(Storage="_boughtdate", DbType="NVarChar(255)")]
		public string boughtdate
		{
			get
			{
				return this._boughtdate;
			}
			set
			{
				if ((this._boughtdate != value))
				{
					this.OnboughtdateChanging(value);
					this.SendPropertyChanging();
					this._boughtdate = value;
					this.SendPropertyChanged("boughtdate");
					this.OnboughtdateChanged();
				}
			}
		}
		
		[Column(Storage="_carbrand", DbType="NVarChar(255)")]
		public string carbrand
		{
			get
			{
				return this._carbrand;
			}
			set
			{
				if ((this._carbrand != value))
				{
					this.OncarbrandChanging(value);
					this.SendPropertyChanging();
					this._carbrand = value;
					this.SendPropertyChanged("carbrand");
					this.OncarbrandChanged();
				}
			}
		}
		
		[Column(Storage="_carmodel", DbType="NVarChar(255)")]
		public string carmodel
		{
			get
			{
				return this._carmodel;
			}
			set
			{
				if ((this._carmodel != value))
				{
					this.OncarmodelChanging(value);
					this.SendPropertyChanging();
					this._carmodel = value;
					this.SendPropertyChanged("carmodel");
					this.OncarmodelChanged();
				}
			}
		}
		
		[Column(Storage="_brochure", DbType="VarChar(50)")]
		public string brochure
		{
			get
			{
				return this._brochure;
			}
			set
			{
				if ((this._brochure != value))
				{
					this.OnbrochureChanging(value);
					this.SendPropertyChanging();
					this._brochure = value;
					this.SendPropertyChanged("brochure");
					this.OnbrochureChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.shouce")]
	public partial class shouce : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _sex;
		
		private string _username;
		
		private string _date;
		
		private string _sheng;
		
		private string _city;
		
		private string _address;
		
		private string _youbian;
		
		private string _email;
		
		private string _dianhua;
		
		private string _shouji;
		
		private string _shouceida;
		
		private string _shouceidb;
		
		private string _shouceid1;
		
		private string _shouceid2;
		
		private string _shouceid3;
		
		private string _shouceid4;
		
		private string _shouceid5;
		
		private string _contactme;
		
		private System.Nullable<System.DateTime> _times;
		
		private string _gcsj;
		
		private string _gcys;
		
		private string _phcx;
		
		private string _phcx1;
		
		private string _phcx2;
		
		private string _phcx3;
		
		private string _phcx4;
		
		private string _phcx5;
		
		private string _td;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OnshengChanging(string value);
    partial void OnshengChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnyoubianChanging(string value);
    partial void OnyoubianChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndianhuaChanging(string value);
    partial void OndianhuaChanged();
    partial void OnshoujiChanging(string value);
    partial void OnshoujiChanged();
    partial void OnshouceidaChanging(string value);
    partial void OnshouceidaChanged();
    partial void OnshouceidbChanging(string value);
    partial void OnshouceidbChanged();
    partial void Onshouceid1Changing(string value);
    partial void Onshouceid1Changed();
    partial void Onshouceid2Changing(string value);
    partial void Onshouceid2Changed();
    partial void Onshouceid3Changing(string value);
    partial void Onshouceid3Changed();
    partial void Onshouceid4Changing(string value);
    partial void Onshouceid4Changed();
    partial void Onshouceid5Changing(string value);
    partial void Onshouceid5Changed();
    partial void OncontactmeChanging(string value);
    partial void OncontactmeChanged();
    partial void OntimesChanging(System.Nullable<System.DateTime> value);
    partial void OntimesChanged();
    partial void OngcsjChanging(string value);
    partial void OngcsjChanged();
    partial void OngcysChanging(string value);
    partial void OngcysChanged();
    partial void OnphcxChanging(string value);
    partial void OnphcxChanged();
    partial void Onphcx1Changing(string value);
    partial void Onphcx1Changed();
    partial void Onphcx2Changing(string value);
    partial void Onphcx2Changed();
    partial void Onphcx3Changing(string value);
    partial void Onphcx3Changed();
    partial void Onphcx4Changing(string value);
    partial void Onphcx4Changed();
    partial void Onphcx5Changing(string value);
    partial void Onphcx5Changed();
    partial void OntdChanging(string value);
    partial void OntdChanged();
    #endregion
		
		public shouce()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_sex", DbType="NVarChar(255)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[Column(Storage="_username", DbType="NVarChar(255)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[Column(Storage="_date", DbType="NVarChar(255)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[Column(Storage="_sheng", DbType="NVarChar(255)")]
		public string sheng
		{
			get
			{
				return this._sheng;
			}
			set
			{
				if ((this._sheng != value))
				{
					this.OnshengChanging(value);
					this.SendPropertyChanging();
					this._sheng = value;
					this.SendPropertyChanged("sheng");
					this.OnshengChanged();
				}
			}
		}
		
		[Column(Storage="_city", DbType="NVarChar(255)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[Column(Storage="_address", DbType="NVarChar(255)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[Column(Storage="_youbian", DbType="NVarChar(255)")]
		public string youbian
		{
			get
			{
				return this._youbian;
			}
			set
			{
				if ((this._youbian != value))
				{
					this.OnyoubianChanging(value);
					this.SendPropertyChanging();
					this._youbian = value;
					this.SendPropertyChanged("youbian");
					this.OnyoubianChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="NVarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[Column(Storage="_dianhua", DbType="NVarChar(255)")]
		public string dianhua
		{
			get
			{
				return this._dianhua;
			}
			set
			{
				if ((this._dianhua != value))
				{
					this.OndianhuaChanging(value);
					this.SendPropertyChanging();
					this._dianhua = value;
					this.SendPropertyChanged("dianhua");
					this.OndianhuaChanged();
				}
			}
		}
		
		[Column(Storage="_shouji", DbType="NVarChar(255)")]
		public string shouji
		{
			get
			{
				return this._shouji;
			}
			set
			{
				if ((this._shouji != value))
				{
					this.OnshoujiChanging(value);
					this.SendPropertyChanging();
					this._shouji = value;
					this.SendPropertyChanged("shouji");
					this.OnshoujiChanged();
				}
			}
		}
		
		[Column(Storage="_shouceida", DbType="NVarChar(255)")]
		public string shouceida
		{
			get
			{
				return this._shouceida;
			}
			set
			{
				if ((this._shouceida != value))
				{
					this.OnshouceidaChanging(value);
					this.SendPropertyChanging();
					this._shouceida = value;
					this.SendPropertyChanged("shouceida");
					this.OnshouceidaChanged();
				}
			}
		}
		
		[Column(Storage="_shouceidb", DbType="NVarChar(255)")]
		public string shouceidb
		{
			get
			{
				return this._shouceidb;
			}
			set
			{
				if ((this._shouceidb != value))
				{
					this.OnshouceidbChanging(value);
					this.SendPropertyChanging();
					this._shouceidb = value;
					this.SendPropertyChanged("shouceidb");
					this.OnshouceidbChanged();
				}
			}
		}
		
		[Column(Storage="_shouceid1", DbType="NVarChar(255)")]
		public string shouceid1
		{
			get
			{
				return this._shouceid1;
			}
			set
			{
				if ((this._shouceid1 != value))
				{
					this.Onshouceid1Changing(value);
					this.SendPropertyChanging();
					this._shouceid1 = value;
					this.SendPropertyChanged("shouceid1");
					this.Onshouceid1Changed();
				}
			}
		}
		
		[Column(Storage="_shouceid2", DbType="NVarChar(255)")]
		public string shouceid2
		{
			get
			{
				return this._shouceid2;
			}
			set
			{
				if ((this._shouceid2 != value))
				{
					this.Onshouceid2Changing(value);
					this.SendPropertyChanging();
					this._shouceid2 = value;
					this.SendPropertyChanged("shouceid2");
					this.Onshouceid2Changed();
				}
			}
		}
		
		[Column(Storage="_shouceid3", DbType="NVarChar(255)")]
		public string shouceid3
		{
			get
			{
				return this._shouceid3;
			}
			set
			{
				if ((this._shouceid3 != value))
				{
					this.Onshouceid3Changing(value);
					this.SendPropertyChanging();
					this._shouceid3 = value;
					this.SendPropertyChanged("shouceid3");
					this.Onshouceid3Changed();
				}
			}
		}
		
		[Column(Storage="_shouceid4", DbType="NVarChar(255)")]
		public string shouceid4
		{
			get
			{
				return this._shouceid4;
			}
			set
			{
				if ((this._shouceid4 != value))
				{
					this.Onshouceid4Changing(value);
					this.SendPropertyChanging();
					this._shouceid4 = value;
					this.SendPropertyChanged("shouceid4");
					this.Onshouceid4Changed();
				}
			}
		}
		
		[Column(Storage="_shouceid5", DbType="NVarChar(50)")]
		public string shouceid5
		{
			get
			{
				return this._shouceid5;
			}
			set
			{
				if ((this._shouceid5 != value))
				{
					this.Onshouceid5Changing(value);
					this.SendPropertyChanging();
					this._shouceid5 = value;
					this.SendPropertyChanged("shouceid5");
					this.Onshouceid5Changed();
				}
			}
		}
		
		[Column(Storage="_contactme", DbType="NVarChar(255)")]
		public string contactme
		{
			get
			{
				return this._contactme;
			}
			set
			{
				if ((this._contactme != value))
				{
					this.OncontactmeChanging(value);
					this.SendPropertyChanging();
					this._contactme = value;
					this.SendPropertyChanged("contactme");
					this.OncontactmeChanged();
				}
			}
		}
		
		[Column(Storage="_times", DbType="DateTime")]
		public System.Nullable<System.DateTime> times
		{
			get
			{
				return this._times;
			}
			set
			{
				if ((this._times != value))
				{
					this.OntimesChanging(value);
					this.SendPropertyChanging();
					this._times = value;
					this.SendPropertyChanged("times");
					this.OntimesChanged();
				}
			}
		}
		
		[Column(Storage="_gcsj", DbType="VarChar(10)")]
		public string gcsj
		{
			get
			{
				return this._gcsj;
			}
			set
			{
				if ((this._gcsj != value))
				{
					this.OngcsjChanging(value);
					this.SendPropertyChanging();
					this._gcsj = value;
					this.SendPropertyChanged("gcsj");
					this.OngcsjChanged();
				}
			}
		}
		
		[Column(Storage="_gcys", DbType="VarChar(10)")]
		public string gcys
		{
			get
			{
				return this._gcys;
			}
			set
			{
				if ((this._gcys != value))
				{
					this.OngcysChanging(value);
					this.SendPropertyChanging();
					this._gcys = value;
					this.SendPropertyChanged("gcys");
					this.OngcysChanged();
				}
			}
		}
		
		[Column(Storage="_phcx", DbType="NVarChar(500)")]
		public string phcx
		{
			get
			{
				return this._phcx;
			}
			set
			{
				if ((this._phcx != value))
				{
					this.OnphcxChanging(value);
					this.SendPropertyChanging();
					this._phcx = value;
					this.SendPropertyChanged("phcx");
					this.OnphcxChanged();
				}
			}
		}
		
		[Column(Storage="_phcx1", DbType="VarChar(10)")]
		public string phcx1
		{
			get
			{
				return this._phcx1;
			}
			set
			{
				if ((this._phcx1 != value))
				{
					this.Onphcx1Changing(value);
					this.SendPropertyChanging();
					this._phcx1 = value;
					this.SendPropertyChanged("phcx1");
					this.Onphcx1Changed();
				}
			}
		}
		
		[Column(Storage="_phcx2", DbType="VarChar(10)")]
		public string phcx2
		{
			get
			{
				return this._phcx2;
			}
			set
			{
				if ((this._phcx2 != value))
				{
					this.Onphcx2Changing(value);
					this.SendPropertyChanging();
					this._phcx2 = value;
					this.SendPropertyChanged("phcx2");
					this.Onphcx2Changed();
				}
			}
		}
		
		[Column(Storage="_phcx3", DbType="VarChar(10)")]
		public string phcx3
		{
			get
			{
				return this._phcx3;
			}
			set
			{
				if ((this._phcx3 != value))
				{
					this.Onphcx3Changing(value);
					this.SendPropertyChanging();
					this._phcx3 = value;
					this.SendPropertyChanged("phcx3");
					this.Onphcx3Changed();
				}
			}
		}
		
		[Column(Storage="_phcx4", DbType="VarChar(10)")]
		public string phcx4
		{
			get
			{
				return this._phcx4;
			}
			set
			{
				if ((this._phcx4 != value))
				{
					this.Onphcx4Changing(value);
					this.SendPropertyChanging();
					this._phcx4 = value;
					this.SendPropertyChanged("phcx4");
					this.Onphcx4Changed();
				}
			}
		}
		
		[Column(Storage="_phcx5", DbType="VarChar(10)")]
		public string phcx5
		{
			get
			{
				return this._phcx5;
			}
			set
			{
				if ((this._phcx5 != value))
				{
					this.Onphcx5Changing(value);
					this.SendPropertyChanging();
					this._phcx5 = value;
					this.SendPropertyChanged("phcx5");
					this.Onphcx5Changed();
				}
			}
		}
		
		[Column(Storage="_td", DbType="VarChar(50)")]
		public string td
		{
			get
			{
				return this._td;
			}
			set
			{
				if ((this._td != value))
				{
					this.OntdChanging(value);
					this.SendPropertyChanging();
					this._td = value;
					this.SendPropertyChanged("td");
					this.OntdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
